using Grandia.Sdk;

namespace GrandiaReduxComplete.Characters;

internal static class Starts
{
    internal static readonly CharacterEdit[] All =
    [
        new()
        {
            Id = CharacterId.Justin,
            JoinLevel = 1,
            StartLevel = 1,
            StartHp = 84,
            StartSp = 100,
            StartMp1 = 50,
            StartMp2 = 40,
            StartMp3 = 30,
            StartStr = 6,
            StartVit = 5,
            StartWit = 3,
            StartAgi = 7,
            StartItems = [Item.WouldSalve, Item.WouldSalve, Item.WouldSalve],
            StartEquip = [Item.WoodenPole, Item.CuttingBoard, Item.AdventureClothes, Item.Goggles, Item.Sneakers, Item.HerosBadge],
        },
        new()
        {
            Id = CharacterId.Feena,
            JoinLevel = 8,
            StartLevel = 10,
            StartHp = 116,
            StartSp = 110,
            StartMp1 = 60,
            StartMp2 = 45,
            StartMp3 = 25,
            StartStr = 30,
            StartVit = 19,
            StartWit = 45,
            StartAgi = 21,
            StartItems = [Item.FirstAidKit, Item.Ginseng, Item.Ginseng, Item.PoisonAntidote367, Item.Panacea, Item.ParingKnife],
            StartEquip = [Item.LeatherWhip, Item.OakenShield, Item.Breastplate, Item.Barrette, Item.LeatherGreaves, Item.JadeCharm],
            VanillaItems = [Item.FirstAidKit, Item.Ginseng, Item.Ginseng, Item.PoisonAntidote367, Item.ParalysisOintment, Item.ParingKnife],
        },
        new()
        {
            Id = CharacterId.Sue,
            JoinLevel = 1,
            StartLevel = 1,
            StartHp = 60,
            StartSp = 100,
            StartMp1 = 50,
            StartMp2 = 40,
            StartMp3 = 30,
            StartStr = 3,
            StartVit = 5,
            StartWit = 13,
            StartAgi = 11,
            // Complete MCHAR: 2 Wound Salve + Toy Hammer. HD vanilla is 2 Squatter + Toy Hammer + Wound Salve.
            StartItems = [Item.WouldSalve, Item.WouldSalve, Item.Banana],
            StartEquip = [Item.ToyBowAndArrow, Item.WoolenMittens, Item.SundayBest, Item.Ribbon, Item.DressShoes, Item.MamasAmulet],
            VanillaItems = [Item.BoxOfSweets, Item.BoxOfSweets, Item.Banana, Item.WouldSalve],
        },
        new()
        {
            Id = CharacterId.Gadwin,
            JoinLevel = 16,
            StartLevel = 30,
            StartHp = 273,
            StartSp = 160,
            StartMp1 = 45,
            StartMp2 = 75,
            StartMp3 = 60,
            StartStr = 116,
            StartVit = 40,
            StartWit = 58,
            StartAgi = 54,
            StartItems = [Item.MikeromaScroll, Item.MikeromaScroll, Item.ResurrectPotion, Item.YellowMedicine, Item.YellowMedicine, Item.Vaccine, Item.Vaccine, Item.Panacea],
            StartEquip = [Item.TheSwordHimmler, Item.DragonGauntlet, Item.ThickArmor, Item.PiratesHelmet, Item.DragonBoots, Item.AncestorsAmulet],
            VanillaItems = [Item.SquidGuts, Item.MikeromaScroll, Item.Vaccine, Item.Vaccine],
        },
        new()
        {
            Id = CharacterId.Rapp,
            JoinLevel = 17,
            StartLevel = 25,
            StartHp = 388,
            StartSp = 220,
            StartMp1 = 80,
            StartMp2 = 60,
            StartMp3 = 50,
            StartStr = 112,
            StartVit = 22,
            StartWit = 98,
            StartAgi = 70,
            StartItems = [Item.CafuShuriken, Item.RedMedicine, Item.RedMedicine, Item.BowColoringBook, Item.MaceColoringBook, Item.RedCrayon, Item.BlueCrayon, Item.SkyBlueCrayon, Item.BrownCrayon],
            StartEquip = [Item.ShockingKnife, Item.AlligatorGauntlet, Item.SpyClothes, Item.Headgear, Item.NinjaSandals, Item.BlackBelt],
            VanillaItems = [Item.RedMedicine, Item.ChocolateCookies, Item.Honey, Item.Vaccine],
        },
        new()
        {
            Id = CharacterId.Milda,
            JoinLevel = 20,
            StartLevel = 40,
            StartHp = 329,
            StartSp = 200,
            StartMp1 = 0,
            StartMp2 = 0,
            StartMp3 = 0,
            StartStr = 200,
            StartVit = 76,
            StartWit = 125,
            StartAgi = 62,
            StartItems = [Item.RedMedicine, Item.RedMedicine, Item.RedMedicine, Item.CampingTent, Item.CampingTent, Item.ResurrectPotion441],
            StartEquip = [Item.WreckingAx, Item.PowerShield, Item.BattleBikini, Item.IronBandana, Item.BeachSandals, Item.TitansRing],
            VanillaItems = [Item.SmokedSalmon, Item.SmokedSalmon, Item.PrimeRib, Item.PrimeRib],
        },
        new()
        {
            Id = CharacterId.Guido,
            JoinLevel = 22,
            StartLevel = 36,
            StartHp = 243,
            StartSp = 160,
            StartMp1 = 0,
            StartMp2 = 0,
            StartMp3 = 0,
            StartStr = 148,
            StartVit = 62,
            StartWit = 227,
            StartAgi = 98,
            StartItems = [Item.YellowMedicine, Item.YellowMedicine, Item.YellowMedicine, Item.BlueMedicine, Item.BlueMedicine, Item.CampingTent, Item.Panacea],
            StartEquip = [Item.PoisonedKnife, Item.MoonlightShield, Item.MogayClothes, Item.FeatheredTurban, Item.RabbitShoes, Item.Scarab],
            VanillaItems = [Item.Panacea, Item.Panacea, Item.LaunchFireworks, Item.LaunchFireworks, Item.RevivalStone, Item.ResurrectPotion, Item.ResurrectPotion],
        },
        new()
        {
            Id = CharacterId.Liete,
            JoinLevel = 24,
            StartLevel = 5,
            StartHp = 69,
            StartSp = 110,
            StartMp1 = 95,
            StartMp2 = 80,
            StartMp3 = 70,
            StartStr = 87,
            StartVit = 80,
            StartWit = 175,
            StartAgi = 26,
            StartItems = [Item.BlueMedicine, Item.BlueMedicine, Item.DeepBluePotion, Item.DeepBluePotion],
            StartEquip = [Item.SparklingRod, Item.MagicGloves, Item.EnchantressRobe, Item.AngelsHat, Item.RainbowHighHeels, Item.HolyRing],
            VanillaItems = [Item.BlueMedicine, Item.BlueMedicine, Item.DeepBluePotion, Item.DeepBluePotion, Item.MagicLipstick, Item.BlackNailPolish],
        },
    ];
}
